config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homes#top'
  get 'home/about',  to: 'homes#about', as: 'home_about'
  resources :books,only: [:create, :show, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
   has_many :books, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resouce)
  	books_path
  end

  def after_sign_out_path_for(resouce)
  	new_user_session_path
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

	def create
		@book = Book.new(book_params)
		@book.user_id = current_user.id #ここがないと保存されず、入力前の画面に戻るのは何故？１対Nの設定と関係あり？
		@book.save
		redirect_to books_path
	end

	def index
		@book = Book.new
		@books = Book.all
	end

	def show
		@books = Book.all
	end

	private
	def book_params
		params.require(:book).permit(:title, :body)
	end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">
			<h1>New Book</h1>
				<%= form_for(@book) do |f| %>
					<h4>タイトル</h4>
					<%= f.text_field :title %>
					<h4>感想</h4>
					<%= f.text_area :body %>
					<br><%= f.submit 'Create Book' %></br>
				<% end %>
		</div>
			<h1>Books一覧</h1>
				<% @books.each do |book| %>
					<p>タイトル</p>
					<span><%= link_to book.title,book_path(book.id) %></span>
					<!-- (book.id)意味はわかるが、book_pathだけで詳細画面に表示されると思っていて、何故(book.id)がないと詳細画面が表示されないのかがわからない、rails routesで決まっている？ -->
				<% end %>
	</div>
</div>

app/views/books/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">
		</div>

			<h1>Book detail</h1>

			<table>
				<thead></thead>
					<tbody>
						<% @books.each do |book| %>
							<tr>
								<td>
									<%= book.title %>
								</td>
								<td>
									<%= book.body %>
								</td>
							</tr>
						<% end %>
					</tbody>
			</table>
	</div>
</div>

app/views/homes/about.html.erb
<h1>Aboutページ</h1>

app/views/homes/top.html.erb
<h1>Bookers2#top</h1>


<%= link_to "Log in", new_user_session_path %>

<%= link_to "Sign Up", new_user_registration_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2Try</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand">Bookers2</a>
    </div>
    <div class="collapse navbar-collapse" id="navbarEexample1">
      <ul class="nav nav-tabs navbar-right">
        <% if user_signed_in? %>
          <li>
            <%= link_to "Home" ,books_path, class: "glyphicon glyphicon-home" %>
          </li>
          <li>
            <%= link_to "Users" ,books_path %>
          </li>
          <li>
            <%= link_to "Books" ,books_path %>
          </li>
          <li>
            <%= link_to "logout",destroy_user_session_path, method: :delete %>
          </li>
        <% else %>
          <li>
            <%= link_to "Home" ,root_path %>
          </li>
          <li>
            <%= link_to "About" ,home_about_path %>
          </li>
          <li>
            <%= link_to "Sign up" ,new_user_registration_path %>
          </li>
          <li>
            <%= link_to "login" ,new_user_session_path %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>


    <%= yield %>
    <div class="">
      CopyRight xxxxxxxx.inc
    </div>
  </body>
</html>